spring:
  application:
    name: urlShortener
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=urlShortener;encrypt=true;trustServerCertificate=true
    username: sa
    password: Admin@123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update   # use 'validate' or 'none' in production
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect
    properties:
      hibernate:
        format_sql: true


jwt:
  secret: mySuperSecretKey1234567890123456  # must be at least 32 characters for HS256
  expiration-ms: 86400000                   # token expiration in milliseconds (1 day)

